### ISSUE TITLE
채팅 구현에 관해

### ISSUE THREAD

**Issue by kimbeopseong** [vsc0705/TripGuide_SW#17]
채팅 구현에 있어서 real time database를 사용한다고 해요!
근데 저희들은 fire store을 주로 사용하니 
https://firebase.google.com/docs/firestore/firestore-for-rtdb?hl=ko
이 방식을 통해서 데이터 매핑하는게 어떨까 하는데 어떻게 생각하시나요?

**Comment by vsc0705** [comment]
https://forest71.tistory.com/category/Android/Firebase
이곳 참고해 보면 realtime database와 병행하지 않아도 채팅 구현이 가능한 것으로 확인되는데 꼭 readtime database와 병행해야 할 이유가 있을까요?

**Comment by kimbeopseong** [comment]
확인했습니다. 그 예제에서와 마찬가지로 real time database 구축후 병행보다는 real time database를 fire store로 변형시키는 방향으로 진행하겠습니다.
