### ISSUE TITLE
db 관련 issue

### ISSUE THREAD

**Issue by KimGyeongHeon** [vsc0705/TripGuide_SW#8]
# DB 관련 코멘트입니다.

#### 그래서 배열이 들어가는 문서를 하나의 컬렉션으로 만들어서 String 형태로 따로따로 저장되는 것이 더 쉽지 않을까 생각합니다.

# 이에 대해 어떻게 생각하시나요?

**Comment by kangdonghune** [comment]
DB에 관해선 잘 몰라서 하는 질문인데 key나 name 값으로 검색해서 정렬하는 방식으로 전체 리스트의 일부를 가져오는 것은 불가능할까요?

**Comment by KimGyeongHeon** [comment]
## User 초기설정은 회원가입 창에서 정보를 다 받는걸로 해결한다. 
## matching_cart는 컬렉션으로 가고 나머지는 그대로 배열로 간다.
## 필요한 것 : 회원가입창 layout 수정

**Comment by KimGyeongHeon** [comment]
### 매칭셋에 질문자 답변자 라디오 버튼 추가
### 라디오 버튼 값에 따라서 보이는 여행기간, 답변 가능시간 나누기
